### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [torhus/monster-browser#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by torhus** [comment]
Hi! I haven't bothered to decide on a licence, since it's always been just a one-man project. Would you prefer it to have a licence? Any preference for which one?

**Comment by suprafun** [comment]
I would , just to be sure of what I can do, I actually just want to learn D and in a game engine context. So your project would be a wonderful resource. I would appreciate a MIT / BSD / zlib license, if its fine for you of course. Thank-you.

**Comment by torhus** [comment]
Right. Although I wouldn't recommend looking too much at the code in this project, since it's an outdated version of D.

**Comment by torhus** [comment]
Are you still interested in this, @suprafun ? This is not a game engine, and it's based on the version of D supported by DMD 1.066, a version of D that's been dead for a while. You are free to borrow pieces of code if you need them for anything, but I'd rather close this issue now if you have lost interest.

**Comment by suprafun** [comment]
Sorry for the delay in my reply, just been busy and I am absent minded. Thank-you so much torhus, I will  take a look at it. Just to learn D from. Thank-you again.
