### ISSUE TITLE
[Idea] Show total server count

### ISSUE THREAD

**Issue by The-Gig** [torhus/monster-browser#21]
I noticed that the total server count (before filtering/checking responsiveness) is only shown during "check for new". I think it might be an useful info also in other situations, especially when one is customizing his mods.ini file and is doing tests. If you think it's not worth keeping it on screen all time, maybe a _tooltip_ when mouseovering on the number of servers in the lower right corner, showing like "Total: 700 servers; responsive: 650; shown: 130".
Just an idea.

**Comment by torhus** [comment]
A tool tip showing the total number of servers was added in v0.9h. Showing how many have responded is still left.
