### ISSUE TITLE
wine (linux) support

### ISSUE THREAD

**Issue by dontdieych** [torhus/monster-browser#27]
Hey, I'm trying to run in linux with wine.

It would be helpful to know what library (dependency) should be installed. Like .Net 4.x, etc.

**Comment by torhus** [comment]
Hi! I don't think you need to install anything extra, at least I didn't.

**Comment by dontdieych** [comment]
```
utris-wrapper: monster-browser
Started initial process 39633 from /usr/bin/wine /home/b/Downloads/MonsterBrowser/MonsterBrowser.exe
Start monitoring process.
esync: up and running.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
tango.core.Exception.LocaleException: Culture not found - if this was not tried set by the application, Tango will expect that a locale is set for the system .
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
```

any advice? runned with wine-staging and lutris.

**Comment by torhus** [comment]
Not sure, it works for me with the version of wine that comes with Linux Mint.

**Comment by torhus** [comment]
@dontdieych I just tried making it build on Linux, but I'm not quite there yet. It shouldn't be too hard to make it build, but there are some parts of the code that are missing Linux versions.

**Comment by dontdieych** [comment]
![image](https://user-images.githubusercontent.com/6509673/193427142-ca1fae0a-c853-4a91-9dfc-25dd4ff0e09b.png)

After installing bunch of dll (dotnet, vc, vb, etc ...) via winetricks,  it's working. Don't know why. :D

Now I'm looking for how to launch native (linux binary or script) linux client directly. `/usr/bin/quake3e`

Thanks! nice app.

**Comment by torhus** [comment]
Cool :) It doesn't use .NET, by the way, it's just native code. Only the standard Windows DLL's are needed, I think they should be included in Wine by default.

> c:\prog\prosjekt\MonsterBrowser_git>dumpbin /dependents MonsterBrowser.exe
> Microsoft (R) COFF/PE Dumper Version 14.33.31630.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> 
> Dump of file MonsterBrowser.exe
> 
> File Type: EXECUTABLE IMAGE
> 
>   Image has the following dependencies:
> 
>     USER32.dll
>     KERNEL32.dll
>     ADVAPI32.DLL
>     COMCTL32.DLL
>     GDI32.DLL
>     SHELL32.DLL
>     SHLWAPI.DLL
>     ole32.DLL
>     OLEAUT32.DLL
>     OLEACC.DLL
>     MSIMG32.DLL
>     USP10.dll
>     WS2_32.DLL
> 
>   Summary
> 
>       191000 .CRT$XIA
>       47D000 .debug
>         4000 .idata
>        26000 .reloc
>         9000 .rsrc
>       160000 _TEXT
> 
> c:\prog\prosjekt\MonsterBrowser_git>

It launches the game by calling the `ShellExecuteA` function, so you should probably stick to ASCII paths to start with. Other than that, I don't know how this works in Wine, but keep trying :)

**Comment by dontdieych** [comment]
Copy server address to clipboard is working well with linux clipboard.

- copy address (ip:port)
- <A-tab> to quake
- open console
- type \connect <C-v> <Enter>

little bit tiresome.

I thought about simple improvement in this case.

how about write `ip:port` to some file? Instead of copy to clipboard. It could be possible watching(monitoring) some file or named pipe or monitoring file change, etc. Then it triggers, run some random command to native quake client.

Thanks.

**Comment by torhus** [comment]
@dontdieych I tried setting MB to launch `/usr/lib/ioquake3/ioquake3`, and it seems to work just fine. The game just makes VirtualBox hang, but I can tell it's connecting to the server.

**Comment by torhus** [comment]
@dontdieych I am closing this now, please reopen if launching the game didn't work for you.

**Comment by dontdieych** [comment]
working well, thanks!
