### ISSUE TITLE
Check for latest version

### ISSUE THREAD

**Issue by torhus** [torhus/monster-browser#32]
### Discussed in https://github.com/torhus/monster-browser/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **The-Gig** October 12, 2022</sup>
The idea is simple: adding a button to allow players to see if a new version of MonsterBrowser has been released.
I suppose the button could just check for an URL pointing to a text file (hosted somewhere in this github?) where you would just write the number of the latest official release, and show that string into a dialog window. So people could easily know that there is a new version available, and the window could contain a link to https://github.com/torhus/monster-browser/releases.

I don't know, maybe it may be part of an "About/Info" menu/screen, where you could also place links to https://sites.google.com/site/monsterbrowser, https://github.com/torhus/monster-browser, and to the included readme.txt and changelog.txt?</div>

**Comment by The-Gig** [comment]
Hi, I see you added "check for new version on startup" in Settings. That's perfectly fine, but I haven't fond a command to force check for updates...
I mean, if I usually don't want the check at startup (maybe fearing it may slow down opening the problem), but today I want to check whether there is a new version... I have to enable the checkbox, close and open the program to see if there are updates, then disable the option again. That's not super comfortable.

Furthermore, the "check for new" (servers) button can still be mistaked for "check for new version"...

**Comment by torhus** [comment]
If you don't want to have the automatic check enabled, why not check the web site, or watch the repository for releases? The automatic update checker actually downloads https://api.github.com/repos/torhus/monster-browser/releases/latest , a 5 kB files that takes less than a second to download. So I wouldn't worry.

By the way, clicking OK after enabling the updater will start it.

**Comment by The-Gig** [comment]
Well, let me think...
1) A single button to click is faster than opening the browser and typing a website.
Of course, if the program included an hyperlink to the website, that might be better than doing by hand.
2) True, it's fast, but people might not know.
3) A popup opening up when you start a program, when you only want to _use_ that program quickly, can be annoying.
4) _Most_ programs I can think about which feature built-in update check have both automatic and mandanual check features, I thought that was quite standard.

_**Just M2C, of course!**_
Don't feel obliged to anything, of course! ;)

**Comment by torhus** [comment]
Yes, but MB has a minimalist interface, no menu bar :)

**Comment by The-Gig** [comment]
... but it has got the Setting windows, which has got room for a button even without enlarging it I think. :)

About "get servers/refresh servers", sounds good I think.
