### ISSUE TITLE
Move mods.ini documentation to the web?

### ISSUE THREAD

**Issue by torhus** [torhus/monster-browser#45]
Should at least flesh it out a bit more now that the Edit button is so prominent.

**Comment by The-Gig** [comment]
I'm not sure about this.
If the goal is to do not clutter the tip of the mods.ini file, why don't move the instructions to the _bottom_ of the file, or to readme file? By the way, the readme file still says "the format of this file is explained in the file itself" (referring to mods.ini), while at the moment it's not strictly true...

**Comment by torhus** [comment]
I figured it's easier to update online documentation. And both mods.ini and the documentation look cleaner this way.

**Comment by The-Gig** [comment]
About documentation, to do not open a whole issue for that, I write here that in the changelog, in the version 0.9f section, you wrote "no no longer", with an extra "no".

**Comment by The-Gig** [comment]
A problem with web documentation is that it's always up-to-date, while the user might be running an older version of the software, where some things may work differently.
So, the instructions specific to previous releases are lost...

**Comment by torhus** [comment]
Well, I hope people won't be using old versions much...
