### ISSUE TITLE
Reorder games

### ISSUE THREAD

**Issue by torhus** [torhus/monster-browser#47]
Should Quake 3 and the mods be first, then other games in descending order of popularity (server count)?

**Comment by The-Gig** [comment]
I was wondering the reason why you placed _smokin' gun_s at the top of the list, and I _guessed_ you didn't choose _Quake3_ for the reason it has got most servers and so it would take more time for the initial search...

**Comment by The-Gig** [comment]
I understand.
However I guess your idea to move Q3 up makes sense, as q3 is already the default game as master server and binaries path.
For now users, of course... No need to wipe one's mods.ini just for that, also considering there is the "start with last mod" option available.

**Comment by The-Gig** [comment]
Also, in case the initial "getting new list" at startup takes too long, so people have to wait before they can switch to another game, maybe disabling the automatic refresh on startup? I don't know.

**Comment by torhus** [comment]
> Also, in case the initial "getting new list" at startup takes too long, so people have to wait before they can switch to another game, maybe disabling the automatic refresh on startup? I don't know.

As it will only get a new master list automatically the first time you start it, I don't think that's a big deal. The automatic refresh can be interrupted.

**Comment by The-Gig** [comment]
Just a note... I tried the Nov 9 2022 beta (from this other discussion <https://github.com/torhus/monster-browser/discussions/51#discussioncomment-4101395>), and noticed that while in that build Quake3 and its mods are at the top of the list there, default settings.ini still comes with "lastMod=Smokin' Guns".
Just a reminder.

**Comment by torhus** [comment]
Thanks, I forgot that!
