### ISSUE TITLE
[Idea] Text search for player name (and more?)

### ISSUE THREAD

**Issue by The-Gig** [torhus/monster-browser#5]
I think it may be nice to add a _filter_ to only list the servers where there is a player whose name corresponds to what you type into a specific field. _That would allow people to quickly find their friends._
As player names may include clan tags and odd symbols, I suggest the search to result positive also for partial comparison (e.g. searching for "sar" would also list servers containing players named "sarge"). Case insensitive of course.

In theory, this may be even expanded to filter for other fields instead of player name, such as _game/gamename_ (as a quick mod search), _hostname_ (e.g. allowing to show the servers from a certain provider) or _map_. But I'm not sure about how to add all of that without adding too much clutter to the GUI. Maybe a single text field, plus a dropdown list to choose in which field perform the search?

**Comment by torhus** [comment]
Monster Browser has been in maintenance mode for years, I'm not likely to add new  features, sorry.

But there is a way to find a player: If you select all servers in the list (Ctrl+A), the player list will also show all players. Enable "Has humans" to hide servers with only bots, and sort players by name. If you find the player you are looking for double click him, or right-click, to go to that server.

The server name used to be shown as a tooltip when you hover over the player name, but that feature seems to be broken, at least on Windows 10. See #7.

**Comment by torhus** [comment]
Reopening this now that I've started experimenting with a search field.

**Comment by torhus** [comment]
Added this in release 0.9f. Thanks for the idea, @The-Gig!

**Comment by The-Gig** [comment]
Thank you!
I'll try it in a few days, I can't right now.
