### ISSUE TITLE
[Idea] Ability to specify command line options to be passed to the game

### ISSUE THREAD

**Issue by The-Gig** [torhus/monster-browser#6]
I was thinking about a secondary feature which might be useful for someone: adding, in mods.ini, _support for passing command line options to the game._

Useful, for example, for passing _+set fs_homepath [path]_ for who wants to use a specific settings folder (e.g. iquake3 and quake3e engines use different folders by default).

Examples:
```
[baseq3 as Clark Kent]
mod=baseq3
cmdOptions=+set name "Clark Kent" +set color 6
[baseq3 as Superman]
mod=baseq3
cmdOptions=+set name Superman +set color 4
```
Of course, the first one means the program would invoke
```
"C:\Program Files\Quake3\Quake3.exe" +set name "Clark Kent" +set color 6 +connect <serveraddress:port>
```

**Comment by torhus** [comment]
There is an easy workaround for this: Create a .lnk or .bat file that contains the parameters, then start the game through that instead. Way more flexible, since you can run any set of commands you like that way.

**Comment by torhus** [comment]
I'm guessing you get an extra window when using a batch file? You can use a shortcut instead to avoid that.

Yeah, it's just a simple way to add flexibility without a lot of work.

**Comment by The-Gig** [comment]
Yes, with the batch file it opens an extra window in the background, which closes when you close the game iirc. _Not a big problem anyway._

The real problem is that I don't see people thinking about doing a such thing...

**Comment by torhus** [comment]
I see this as more of an advanced feature, so I'm not that worried. I could change the documentation for exePath to make this feature more discoverable, what do you think?

```
; exePath - Only used if regKey or exeName are missing. If exePath is missing
;           too, gamePath from the global settings is used instead. Adding 
;           extra parameters or startup commands can by done by using batch
;           (.bat) files or shortcut (.lnk) files instead of running the
;           executable directly.
```
I removed the example path, as there are examples in the included game configs.

**Comment by The-Gig** [comment]
Nice, but the % variables is important, I guess most people don't know about them.

So maybe:
"Adding extra parameters or startup commands can BE done by POINTING TO batch (.bat) files or shortcut (.lnk) files instead of running the executable directly. Such .bat or .lnk should include the real .exe, your custom commands and %1 %2 (example: quake3.exe +set name "My name" %1 %2)."

What do you think?

**Comment by torhus** [comment]
The % batch file variables won't be of much use here, they will just bet the arguments that MB adds when launching the game. %1 is `+set`, %2 is `fs_game` etc. If you are thinking about things like `%ProgramFiles%`, those are environment variables.

**Comment by The-Gig** [comment]
I'm not talking about environment variables, but about variables you can pass like command line parameters when launching a batch file.

When I did my test today, I noticed that MB passed +connect as %1 and serveradress as %2. If the batch file did not mention %1 %2, then MB would only have started the game, but the game would not have connected to any server.
I haven't yet tried whether they are necessary for .lnk files... But to have our trick working with a .bat file we need them. Try...

**Comment by torhus** [comment]
Right, my mistake. And I guess that makes .lnk files useless in this context. I think this is an argument for adding this feature.

**Comment by The-Gig** [comment]
Done a few tests with .lnk file. I see there you must _not_ include the %1 %2, otherwise it messes up.

So, let's try again:
_Adding extra parameters or startup commands can be done by pointing to batch (.bat) files or shortcut (.lnk) files instead of running the executable directly. A such .bat should mention the real .exe, your custom commands and %1 %2 (example: "quake3.exe" +set name "My name" %1 %2), while a such .lnk should not include %1 %2 (example: "C:\Q3A\quake3.exe" +set name "My name" )._
